apiVersion: apps/v1
kind: Deployment
metadata:
  name: godot-agones
  namespace: default
  labels:
    app: godot-agones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: godot-agones
  template:
    metadata:
      labels:
        app: godot-agones
    spec:
      serviceAccount: godot-agones
      containers:
      - name: godot-agones
        image: bosakmaw/godot-agones:server
        imagePullPolicy: Always
        ports:
        - name: godot-agones
          containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 200M 
---
apiVersion: v1
kind: Service
metadata:
  name: godot-agones
  labels:
    app: godot-agones
spec:
  type: NodePort
  selector:
    app: godot-agones
  ports:
  - port: 9410
    protocol: TCP
    name: http
    targetPort: godot-agones
    nodePort: 30941
